spring:
  data:
    mongodb:
      database: demo
      uri: mongodb://localhost:27017/?directConnection=true

org:
  jobrunr:
    database:
      database-name: demo
      type: mongodb
      table-prefix: jobrunr-
    background-job-server:
      thread-type: virtualthreads
      enabled: true

server:
  port: 8089
